const CATEGORIES = {
  BASICS: "基礎文法",
  FUNCTIONS: "関数・スコープ",
  ASYNC: "非同期処理",
  ES6: "ES6+",
  DOM: "DOM操作",
  ERROR: "エラー処理",
};

const LEVELS = {
  BEGINNER: "初級",
  INTERMEDIATE: "中級",
  ADVANCED: "上級",
};

const questions = [
  // ── 基礎文法 ──────────────────────────────────────────────
  {
    id: 1,
    category: CATEGORIES.BASICS,
    level: LEVELS.BEGINNER,
    question: "次のコードの出力結果は？\n\nconsole.log(typeof null);",
    choices: ["'null'", "'object'", "'undefined'", "'boolean'"],
    answer: 1,
    explanation: "typeof null は歴史的なバグにより 'object' を返します。",
  },
  {
    id: 2,
    category: CATEGORIES.BASICS,
    level: LEVELS.BEGINNER,
    question: "次のうち、falsy な値はどれですか？",
    choices: ["'false'（文字列）", "[]（空配列）", "0", "{}（空オブジェクト）"],
    answer: 2,
    explanation: "0 は falsy です。空文字列 ''、null、undefined、NaN も falsy です。'false' は空でない文字列なので truthy です。",
  },
  {
    id: 3,
    category: CATEGORIES.BASICS,
    level: LEVELS.BEGINNER,
    question: "var・let・const の違いで正しいのは？",
    choices: [
      "var はブロックスコープ、let はグローバルスコープ",
      "const は再宣言不可、let は再宣言可能",
      "let と const はブロックスコープ、var は関数スコープ",
      "const で宣言したオブジェクトのプロパティは変更できない",
    ],
    answer: 2,
    explanation: "let/const はブロックスコープ、var は関数スコープです。const はバインディングを再代入できませんが、オブジェクトのプロパティは変更可能です。",
  },
  {
    id: 4,
    category: CATEGORIES.BASICS,
    level: LEVELS.INTERMEDIATE,
    question: "次のコードの出力は？\n\nconsole.log(1 + '2' + 3);",
    choices: ["6", "'123'", "'15'", "NaN"],
    answer: 1,
    explanation: "1 + '2' は文字列連結で '12' になり、'12' + 3 で '123' になります。",
  },
  {
    id: 5,
    category: CATEGORIES.BASICS,
    level: LEVELS.INTERMEDIATE,
    question: "== と === の違いで正しいのは？",
    choices: [
      "== は厳密比較、=== は型変換あり比較",
      "== は型変換あり比較、=== は厳密比較",
      "どちらも同じ結果を返す",
      "=== はオブジェクトの比較専用",
    ],
    answer: 1,
    explanation: "== は型強制（type coercion）を行います。例えば 0 == false は true ですが、0 === false は false です。",
  },
  {
    id: 6,
    category: CATEGORIES.BASICS,
    level: LEVELS.ADVANCED,
    question: "次のコードの出力は？\n\nconsole.log(0.1 + 0.2 === 0.3);",
    choices: ["true", "false", "undefined", "エラーが発生する"],
    answer: 1,
    explanation: "浮動小数点数の精度問題により、0.1 + 0.2 は 0.30000000000000004 になります。Number.EPSILON を使って比較するのが正しい方法です。",
  },

  // ── 関数・スコープ ─────────────────────────────────────────
  {
    id: 7,
    category: CATEGORIES.FUNCTIONS,
    level: LEVELS.BEGINNER,
    question: "次のコードの出力は？\n\nconsole.log(add(2, 3));\nfunction add(a, b) { return a + b; }",
    choices: ["エラーが発生する", "undefined", "5", "NaN"],
    answer: 2,
    explanation: "関数宣言はホイスティングされるため、宣言前に呼び出しても動作します。",
  },
  {
    id: 8,
    category: CATEGORIES.FUNCTIONS,
    level: LEVELS.INTERMEDIATE,
    question: "クロージャの説明として正しいのは？",
    choices: [
      "クラスのプライベートメソッドのこと",
      "関数が定義されたスコープの変数にアクセスできる仕組み",
      "即時実行関数（IIFE）の別名",
      "メモリリークを防ぐための機能",
    ],
    answer: 1,
    explanation: "クロージャは、関数がその外側のスコープの変数を記憶し参照し続ける仕組みです。カウンターや状態の保持によく使われます。",
  },
  {
    id: 9,
    category: CATEGORIES.FUNCTIONS,
    level: LEVELS.INTERMEDIATE,
    question: "次のコードの出力は？\n\nconst obj = {\n  val: 10,\n  get() { return this.val; }\n};\nconst fn = obj.get;\nconsole.log(fn());",
    choices: ["10", "undefined", "null", "エラーが発生する"],
    answer: 1,
    explanation: "メソッドをオブジェクトから切り離して呼び出すと this はグローバルオブジェクト（strictモードでは undefined）になるため、this.val は undefined になります。",
  },
  {
    id: 10,
    category: CATEGORIES.FUNCTIONS,
    level: LEVELS.INTERMEDIATE,
    question: "次のコードの出力は？\n\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
    choices: ["0 1 2", "3 3 3", "0 0 0", "1 2 3"],
    answer: 1,
    explanation: "var はブロックスコープを持たず、setTimeout のコールバックが実行される時点で i はすでに 3 です。let を使うとブロックスコープにより 0 1 2 になります。",
  },
  {
    id: 11,
    category: CATEGORIES.FUNCTIONS,
    level: LEVELS.ADVANCED,
    question: "カリー化（Currying）の説明として正しいのは？",
    choices: [
      "複数の関数を合成する手法",
      "複数引数の関数を1引数の関数のチェーンに変換する手法",
      "再帰関数を最適化する手法",
      "メモ化（memoization）の別名",
    ],
    answer: 1,
    explanation: "カリー化は f(a, b, c) を f(a)(b)(c) に変換する手法です。部分適用や関数合成と相性が良く、関数型プログラミングで多用されます。",
  },
  {
    id: 12,
    category: CATEGORIES.FUNCTIONS,
    level: LEVELS.ADVANCED,
    question: "次のコードの出力は？\n\nfunction* gen() {\n  yield 1;\n  yield 2;\n  yield 3;\n}\nconst g = gen();\nconsole.log(g.next().value);",
    choices: ["[1, 2, 3]", "1", "undefined", "Generator {}"],
    answer: 1,
    explanation: "ジェネレーター関数は呼び出すとジェネレーターオブジェクトを返します。next() を呼ぶたびに次の yield の値が返されます。最初の next() では yield 1 なので 1 が返ります。",
  },

  // ── 非同期処理 ─────────────────────────────────────────────
  {
    id: 13,
    category: CATEGORIES.ASYNC,
    level: LEVELS.BEGINNER,
    question: "Promise の状態として存在しないのはどれですか？",
    choices: ["pending", "fulfilled", "rejected", "resolved"],
    answer: 3,
    explanation: "Promise の状態は pending（待機中）、fulfilled（成功）、rejected（失敗）の3つです。'resolved' は状態名ではなく、fulfilled または rejected になったことを指す用語として使われることがありますが、公式な状態ではありません。",
  },
  {
    id: 14,
    category: CATEGORIES.ASYNC,
    level: LEVELS.INTERMEDIATE,
    question: "次のコードで最初にコンソールに出力されるのは？\n\nconsole.log('A');\nsetTimeout(() => console.log('B'), 0);\nPromise.resolve().then(() => console.log('C'));\nconsole.log('D');",
    choices: ["A B C D", "A D C B", "A D B C", "A C D B"],
    answer: 1,
    explanation: "同期処理 → マイクロタスク（Promise） → マクロタスク（setTimeout）の順で実行されます。A→D（同期）→C（Promise/マイクロタスク）→B（setTimeout/マクロタスク）",
  },
  {
    id: 15,
    category: CATEGORIES.ASYNC,
    level: LEVELS.INTERMEDIATE,
    question: "async/await について正しいのは？",
    choices: [
      "async 関数は常に同期的に実行される",
      "await は Promise 以外の値には使えない",
      "async 関数は常に Promise を返す",
      "try/catch では async 関数のエラーを捕捉できない",
    ],
    answer: 2,
    explanation: "async 関数は必ず Promise を返します。返り値が Promise でない場合も、自動的に Promise.resolve() でラップされます。",
  },
  {
    id: 16,
    category: CATEGORIES.ASYNC,
    level: LEVELS.INTERMEDIATE,
    question: "Promise.all と Promise.allSettled の違いは？",
    choices: [
      "Promise.all は直列実行、Promise.allSettled は並列実行",
      "Promise.all はひとつでも reject されると失敗、Promise.allSettled は全て完了を待つ",
      "Promise.all は最初に resolve したものを返す",
      "違いはなく、どちらも同じ動作をする",
    ],
    answer: 1,
    explanation: "Promise.all はひとつでも reject されると即座に reject します。Promise.allSettled は全ての Promise が完了（fulfilled/rejected 問わず）するまで待ち、全結果を返します。",
  },
  {
    id: 17,
    category: CATEGORIES.ASYNC,
    level: LEVELS.ADVANCED,
    question: "次のコードの出力は？\n\nasync function foo() {\n  return 1;\n}\nasync function bar() {\n  const x = await foo();\n  console.log(x);\n}\nbar();\nconsole.log('end');",
    choices: ["1 end", "end 1", "end\n1（別行）", "エラーが発生する"],
    answer: 1,
    explanation: "bar() 内の await で一時停止し、同期処理の 'end' が先に出力されます。その後マイクロタスクとして 1 が出力されます。",
  },

  // ── ES6+ ──────────────────────────────────────────────────
  {
    id: 18,
    category: CATEGORIES.ES6,
    level: LEVELS.BEGINNER,
    question: "アロー関数 (=>) と通常の function の主な違いは？",
    choices: [
      "アロー関数は引数を持てない",
      "アロー関数は自身の this を持たない",
      "アロー関数はメソッドとして使えない",
      "アロー関数は非同期処理に使えない",
    ],
    answer: 1,
    explanation: "アロー関数は自身の this を持たず、外側のスコープの this をそのまま使います。そのためオブジェクトのメソッドで使う際は注意が必要です。",
  },
  {
    id: 19,
    category: CATEGORIES.ES6,
    level: LEVELS.BEGINNER,
    question: "テンプレートリテラルで正しい書き方は？",
    choices: [
      "\"Hello, ${name}!\"",
      "'Hello, ${name}!'",
      "`Hello, ${name}!`",
      "<Hello, ${name}!>",
    ],
    answer: 2,
    explanation: "テンプレートリテラルはバッククォート（`）で囲み、式は ${} で埋め込みます。",
  },
  {
    id: 20,
    category: CATEGORIES.ES6,
    level: LEVELS.INTERMEDIATE,
    question: "次のコードの出力は？\n\nconst [a, , b] = [1, 2, 3];\nconsole.log(a, b);",
    choices: ["1 2", "1 3", "2 3", "undefined undefined"],
    answer: 1,
    explanation: "分割代入でカンマを使うと要素をスキップできます。a=1、2はスキップ、b=3 になります。",
  },
  {
    id: 21,
    category: CATEGORIES.ES6,
    level: LEVELS.INTERMEDIATE,
    question: "スプレッド構文の説明として正しいのは？",
    choices: [
      "オブジェクトのプロパティをコピーできないが、配列は可能",
      "配列やオブジェクトを展開・コピーできる",
      "レスト引数（...args）と全く同じ機能",
      "ES2020 で導入された比較的新しい構文",
    ],
    answer: 1,
    explanation: "スプレッド構文（...）は配列・オブジェクトの浅いコピーや結合に使えます。レスト引数も同じ記法ですが、引数をまとめる逆の操作です。",
  },
  {
    id: 22,
    category: CATEGORIES.ES6,
    level: LEVELS.ADVANCED,
    question: "WeakMap と Map の違いで正しいのは？",
    choices: [
      "WeakMap はキーに文字列のみ使用可能",
      "WeakMap はガベージコレクションを妨げない弱い参照を持つ",
      "WeakMap は通常の Map より処理が速い",
      "WeakMap はイテラブルでサイズを取得できる",
    ],
    answer: 1,
    explanation: "WeakMap のキーはオブジェクトのみで、弱い参照のため他に参照がなくなるとGCで回収されます。イテレーションや size プロパティは持ちません。",
  },

  // ── DOM操作 ────────────────────────────────────────────────
  {
    id: 23,
    category: CATEGORIES.DOM,
    level: LEVELS.BEGINNER,
    question: "document.querySelector('#main') が返すのは？",
    choices: [
      "id='main' の要素の配列",
      "id='main' の最初の要素（1つ）",
      "id='main' の全要素の NodeList",
      "id='main' の要素が存在しない場合は空配列",
    ],
    answer: 1,
    explanation: "querySelector は条件に一致する最初の要素を返します。存在しない場合は null を返します。全要素を取得するには querySelectorAll を使います。",
  },
  {
    id: 24,
    category: CATEGORIES.DOM,
    level: LEVELS.INTERMEDIATE,
    question: "イベントバブリングの説明として正しいのは？",
    choices: [
      "子要素のイベントが親要素へ伝播していく仕組み",
      "親要素のイベントが子要素へ伝播していく仕組み",
      "同じ要素内で複数のイベントが発火する仕組み",
      "非同期イベントの処理順序を管理する仕組み",
    ],
    answer: 0,
    explanation: "バブリングは子要素のイベントが親・祖先要素へと伝播する仕組みです。event.stopPropagation() で止められます。逆方向（上から下）はキャプチャリングと呼びます。",
  },
  {
    id: 25,
    category: CATEGORIES.DOM,
    level: LEVELS.INTERMEDIATE,
    question: "innerHTML と textContent の使い分けで正しいのは？",
    choices: [
      "innerHTML は高速、textContent は低速",
      "XSSリスクがあるため、ユーザー入力には textContent が安全",
      "textContent はHTMLタグも含めてテキストとして出力する",
      "どちらも全く同じ動作をする",
    ],
    answer: 1,
    explanation: "innerHTML はHTMLとして解釈されるため、ユーザー入力をそのまま使うとXSSの脆弱性になります。テキストとして扱う場合は textContent を使うのが安全です。",
  },
  {
    id: 26,
    category: CATEGORIES.DOM,
    level: LEVELS.ADVANCED,
    question: "イベント委譲（Event Delegation）のメリットは？",
    choices: [
      "イベントの発火速度が上がる",
      "動的に追加された子要素にも対応でき、メモリ効率が良い",
      "preventDefault() が不要になる",
      "Shadow DOM と連携しやすくなる",
    ],
    answer: 1,
    explanation: "イベント委譲は親要素にリスナーを一つ登録し、バブリングを利用して複数の子要素のイベントを処理する手法です。動的追加要素への対応とリスナー数の削減が主なメリットです。",
  },

  // ── エラー処理 ─────────────────────────────────────────────
  {
    id: 27,
    category: CATEGORIES.ERROR,
    level: LEVELS.BEGINNER,
    question: "try/catch/finally について正しいのは？",
    choices: [
      "finally は catch ブロックがある場合のみ実行される",
      "finally はエラーの有無にかかわらず必ず実行される",
      "catch ブロックは必ず記述しなければならない",
      "finally 内でエラーが発生すると元のエラーが保持される",
    ],
    answer: 1,
    explanation: "finally はエラーの有無にかかわらず必ず実行されます。catch は省略可能（try/finally も有効）です。finally 内でエラーが発生すると元のエラーは上書きされます。",
  },
  {
    id: 28,
    category: CATEGORIES.ERROR,
    level: LEVELS.INTERMEDIATE,
    question: "カスタムエラーを作成する正しい方法は？",
    choices: [
      "const err = { message: 'error', type: 'CustomError' };",
      "class CustomError extends Error { constructor(msg) { super(msg); this.name = 'CustomError'; } }",
      "function CustomError(msg) { return new Error(msg); }",
      "throw { message: msg, stack: new Error().stack };",
    ],
    answer: 1,
    explanation: "Error クラスを継承してカスタムエラーを作ります。super(msg) でメッセージを設定し、this.name でエラー名を設定します。instanceof での判定も正しく動作します。",
  },
  {
    id: 29,
    category: CATEGORIES.ERROR,
    level: LEVELS.INTERMEDIATE,
    question: "Promise のエラーを処理する方法として適切でないのは？",
    choices: [
      ".catch(err => ...) を使う",
      "async/await と try/catch を組み合わせる",
      ".then(null, err => ...) を使う",
      "try/catch で Promise を直接囲む（await なし）",
    ],
    answer: 3,
    explanation: "await なしで Promise を try/catch で囲んでもエラーを捕捉できません。Promise は非同期なため、エラーは .catch() か、async 関数内で await + try/catch を使う必要があります。",
  },
  {
    id: 30,
    category: CATEGORIES.ERROR,
    level: LEVELS.ADVANCED,
    question: "unhandledRejection イベントの説明として正しいのは？",
    choices: [
      "同期エラーがどこでも捕捉されなかった場合に発火する",
      "Promise の rejection が .catch() で処理されなかった場合に発火する",
      "try/catch ブロックを抜けた後に発火する",
      "Node.js でのみ存在し、ブラウザには存在しない",
    ],
    answer: 1,
    explanation: "unhandledRejection は未処理の Promise rejection を検知するイベントです。Node.js では process.on('unhandledRejection', ...) 、ブラウザでは window.addEventListener('unhandledrejection', ...) で捕捉できます。",
  },
];

export { questions, CATEGORIES, LEVELS };
